### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ProAngelGR** [vik1395/ProtectionStones-Minecraft#2]
`[01:07:50] [Server thread/ERROR]: Could not load 'plugins/ProtectionStones.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/vik1395/ProtectionStones/Main : Unsupported major.minor version 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.UnsupportedClassVersionError: me/vik1395/ProtectionStones/Main : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_71]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_71]
    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_71]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
    ... 6 more`

**Comment by Dragoboss** [comment]
What is the JAVA version of the machine you're running your server on?

'java.lang.UnsupportedClassVersionError' is caused when the JAVA version used for compiling is more recent than the executing JAVA version and no longer supports this older version.

Easiest fix would be updating your JAVA to 1.8.

**Comment by Dragoboss** [comment]
What is the JAVA version of the machine you're running your server on?

'java.lang.UnsupportedClassVersionError' is caused when the JAVA version used for compiling is more recent than the executing JAVA version and no longer supports this older version.

Easiest fix would be updating your JAVA to 1.8.

**Comment by ProAngelGR** [comment]
You can't do it combatible with java 1.7 ?

**Comment by vik1395** [comment]
Just changed to compiling with Java 7 in the new update (https://github.com/vik1395/ProtectionStones-Minecraft/commit/3438686e74b381f7c4125a8d20b63265be18cddb) . This should help fix your issue. download it here: https://github.com/vik1395/ProtectionStones-Minecraft/raw/master/target/ProtectionStones-1.4.1.jar
