### ISSUE TITLE
Plugin does not start up on 1.13

### ISSUE THREAD

**Issue by PhanaticD** [vik1395/ProtectionStones-Minecraft#39]
```
[07:36:37] [Server thread/ERROR]: Could not load 'plugins/ProtectionStones.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.13.2.jar:git-Paper-474]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.13.2.jar:git-Paper-474]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.13.2.jar:git-Paper-474]
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:329) ~[patched_1.13.2.jar:git-Paper-474]
    at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-474]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-474]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.13.2.jar:git-Paper-474]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.13.2.jar:git-Paper-474]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-474]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-474]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.13.2.jar:git-Paper-474]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.13.2.jar:git-Paper-474]
    ... 6 more
```

**Comment by jerzean** [comment]
this has been fixed with the latest update
